### ISSUE TITLE
Input cycling

### ISSUE THREAD

**Issue by ghost** [nph278/integral#1]
Admittedly, implicit input is a really nice thing in Integral. However, when I initially used Integral, I expected the input to cycle when the interpreter runs out of inputs. E.g.
```
►
```
Currently, for the input `1`, this produces `NaN`. It's probably good to prevent that from happening, by implementing input cycling: when you run out of implicit inputs, you cycle back to the first input and start again.

**Comment by A-ee** [comment]
In addition, you can implement single character strings, since `⌡x⌡` is quite cumbersome to just push x. E.g. you can use `~x` to push the character x, but the specifics totally depends on you.

**Comment by A-ee** [comment]
You probably also want to add some built-ins for powers of 2, since these numbers come up in real challenges quite often. I.e. you will have built-ins for 16, 32, 64, 128, 256, 512, 1024, 2048, etc.

**Comment by nph278** [comment]
I added character pushing and some powers of two.

**Comment by ghost** [comment]
So do you like the idea of input cycling or not? If you like it, I'm going to implement it myself anyway.
<hr/>
Given that you have spread onto stack, why don't you have wrap everything on stack onto list?

Also, since you have eval, why not implement an un-eval in Integral?

In addition, is printing everything on the stack joined by newlines a default of the language? Implicitly outputting everything on the stack is certainly useful, but the extra newlines can get quite cumbersome sometimes, in practical CGCC challenges.

**Comment by A-ee** [comment]
Given that you have spread onto stack, why don't you have roll everything on stack onto list? In addition, is printing everything on the stack joined by newlines a default of the language?

**Comment by nph278** [comment]
Yes, you can add it yourself.

**Comment by A-ee** [comment]
@nph278 Okay, I did that. I intended to also add wrap stack and un-eval.
