### ISSUE TITLE
Joining doesn't work

### ISSUE THREAD

**Issue by lyxal** [nph278/integral#12]
Say I have this program:

    ⌡^♦^P◙⌡^♦^P◙

(It's a quine)

This error appears in the developer console:

```
Uncaught TypeError: a.join is not a function
    at runlang (integral.js:452)
    at HTMLButtonElement.onclick ((index):43)
```

**Comment by ghost** [comment]
I think you've did too much 05AB1E... :P Integral is strictly typed, so it will never let you join the entire stack. You can only use it to join a single list.

[`⌡^♦►◙►⌡^♦►◙►` (12 bytes)](https://a-ee.github.io/integral/?code=9V4EEAoQ9V4EEAoQ&input=ICAgICAgICA) solves the problem, BTW.
