### ISSUE TITLE
Remove all references to a-ee.github.io / a-ee's repository 

### ISSUE THREAD

**Issue by lyxal** [nph278/integral#22]
They deleted their account and the links no longer work.

**Comment by nph278** [comment]
I could not find any references.

**Comment by nph278** [comment]
If I missed any, just put them here

**Comment by lyxal** [comment]
Also, if you opened https://a-ee.github.io/integral/, that might be another reason that your answer doesn't work. Use https://nph278.github.io/integral/ - that interpreter is more stable, and has a higher change of working out.

**Comment by lyxal** [comment]
. If you want to take a look at the entire codepage, you can go to constants.js.

It links to a deleted repository

**Comment by nph278** [comment]
Thanks, I will fix those.
