### ISSUE TITLE
While Loops!

### ISSUE THREAD

**Issue by lyxal** [nph278/integral#3]
Every language needs some sort of way to loop while a condition is true.

An idea:

`{...}` runs the code in the `{}` while the top of the stack is truthy

**Comment by ghost** [comment]
As per the usual syntax of Integral programs, you should probably propose like this:

`⌡...⌡{` runs the code in the `⌡...⌡` while the top of the stack is truthy (does not pop items off the stack)

**Comment by lyxal** [comment]
But then what if I want a loop inside my loop? I can't do `⌡⌡...⌡{⌡{` because that's not how strings work.

**Comment by nph278** [comment]
I am working on this now.

**Comment by nph278** [comment]
I think I an going to use the `⌡...⌡{` syntax for now.

**Comment by A-ee** [comment]
> But then what if I want a loop inside my loop? I can't do `⌡⌡...⌡{⌡{` because that's not how strings work.

I think that is bad programming practice. A well-golfed and readable program will never use nested loops at all.
