### ISSUE TITLE
New interpreter

### ISSUE THREAD

**Issue by nph278** [nph278/integral#9]
For now on, the interpreter link should be 

https://nph278.github.io/integral/index.html

**Comment by A-ee** [comment]
An issue of my interpreter: Unfortunately the byte counter of my interpreter fails when you modify the code after execution. I'll try my best to fix that.

**Comment by ghost** [comment]
A final thing for me to implement in the interpreter here: dynamic instruction indexing. If you ever used the dev mode of the online [Canvas](https://dzaima.github.io/Canvas/) interpreter, you'll realize that this mode is extremely convenient.

How this will work:

* When the query string is empty, return the entire table.
* When the query string only consists of a single character, return all instructions called this single character.
* When the query string consists of 2 or more characters, return all entries of the table with a substring matching this query. (The query string is whitespace insensitive and capitalization insensitive)

**Comment by A-ee** [comment]
Another bug: the programs linked by the SE post template are un-editable.
